export const testIds = {
  appConfig: {
    apiKey: 'data-testid ac-api-key',
    apiUrl: 'data-testid ac-api-url',
    submit: 'data-testid ac-submit-form',
    testConnection: 'data-testid ac-test-connection',
    testStatus: 'data-testid ac-test-status',
    debugLog: 'data-testid ac-debug-log',
    showContext: 'data-testid ac-show-context',
    sendGrafanaEvidence: 'data-testid ac-send-evidence',
  },
  dotai: {
    container: 'data-testid dotai-container',
    intent: 'data-testid dotai-intent',
    submit: 'data-testid dotai-submit',
    response: 'data-testid dotai-response',
    error: 'data-testid dotai-error',
    loading: 'data-testid dotai-loading',
    tool: 'data-testid dotai-tool',
    history: 'data-testid dotai-history',
    current: 'data-testid dotai-current',
    map: 'data-testid dotai-map',
    clearThread: 'data-testid dotai-clear-thread',
    analyzeThis: 'data-testid dotai-analyze-this',
    retry: 'data-testid dotai-retry',
    cancel: 'data-testid dotai-cancel',
    consent: 'data-testid dotai-consent',
    drilldown: 'data-testid dotai-drilldown',
  },
};
